FROM node:lts as dependencies
WORKDIR /my-project
COPY package.json ./
RUN yarn install --frozen-lockfile

FROM node:lts as builder

ARG APP_STAGE
ARG API_BASE_URL
ARG CLIENT_KEY

WORKDIR /my-project
COPY . .
COPY --from=dependencies /my-project/node_modules ./node_modules

ENV NEXT_PUBLIC_APP_STAGE=$APP_STAGE
ENV NEXT_PUBLIC_API_BASE_URL=$API_BASE_URL
ENV NEXT_PUBLIC_CLIENT_KEY=$CLIENT_KEY

RUN echo "App host url is $NEXT_PUBLIC_API_BASE_URL"

RUN yarn build

FROM node:lts as runner
WORKDIR /my-project

# If you are using a custom next.config.js file, uncomment this line.
COPY --from=builder /my-project/next.config.ts ./
COPY --from=builder /my-project/postcss.config.mjs ./
COPY --from=builder /my-project/eslint.config.mjs ./
COPY --from=builder /my-project/tsconfig.json ./
COPY --from=builder /my-project/public ./public
COPY --from=builder /my-project/.next ./.next
COPY --from=builder /my-project/node_modules ./node_modules
COPY --from=builder /my-project/package.json ./package.json

EXPOSE 3000
CMD ["yarn", "start"]
